        name: Deploy over SSH (Alibaba)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.ALI_DEPLOY_HOST }}
          username: ${{ secrets.ALI_DEPLOY_USER }}
          key: ${{ secrets.ALI_DEPLOY_SSH_KEY }}
          passphrase: ${{ secrets.ALI_DEPLOY_SSH_PASSPHRASE }}
          port: 22
          script: |
            set -euo pipefail
            getent hosts github.com >/dev/null
            curl -sSfI https://github.com -m 10 >/dev/null

            sudo -u myapp bash -s <<'REMOTE'
            set -euo pipefail
            cd /srv/myapp/repo
            git remote set-url origin git@github.com:Mrdoker1/Taro.git || true
            git fetch origin main --quiet
            git checkout main || git checkout -b main
            git pull --ff-only

            if [ -f package-lock.json ]; then
              npm ci
            else
              npm install --no-audit --no-fund
            fi
            npm run build

            # Create .deploy_info file with deployment metadata (commit SHA and UTC timestamp)
            # Used for tracking deployed version and deployment time
            echo "sha=${GITHUB_SHA} time=$(date -u +%Y-%m-%dT%H:%M:%SZ)" > .deploy_info

            if pm2 describe myapp-api >/dev/null 2>&1; then
              pm2 restart myapp-api --update-env
            else
              pm2 start "npm start" --name myapp-api --time
            fi

            pm2 save
            echo "ALIBABA DEPLOYED $(cat .deploy_info)"
            REMOTE
